
import { createClient } from '@supabase/supabase-js';

// --- START OF TYPE DEFINITIONS ---
export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export type AttendanceStatusEnum = 'Hadir' | 'Sakit' | 'Izin' | 'Alfa';

export interface Database {
  public: {
    Tables: {
      students: {
        Row: {
          id: number
          created_at: string
          name: string
          class: string
          nis: string
          email: string | null
          user_id: string
        }
        Insert: {
          id?: number
          created_at?: string
          name: string
          class: string
          nis?: string
          email?: string | null
          user_id?: string
        }
        Update: {
          id?: number
          created_at?: string
          name?: string
          class?: string
          nis?: string
          email?: string | null
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "students_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "users"
            referencedColumns: ["id"]
          }
        ]
      }
      attendance_records: {
        Row: {
          id: number
          created_at: string
          student_id: number
          date: string
          lesson_hour: number
          status: AttendanceStatusEnum
          user_id: string
        }
        Insert: {
          id?: number
          created_at?: string
          student_id: number
          date: string
          lesson_hour: number
          status: AttendanceStatusEnum
          user_id?: string
        }
        Update: {
          id?: number
          created_at?: string
          student_id?: number
          date?: string
          lesson_hour?: number
          status?: AttendanceStatusEnum
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "attendance_records_student_id_fkey"
            columns: ["student_id"]
            isOneToOne: false
            referencedRelation: "students"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "attendance_records_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "users"
            referencedColumns: ["id"]
          }
        ]
      }
    }
    Views: { [key: string]: never }
    Functions: {
      save_class_attendance: {
        Args: {
          records_json: Json
        }
        Returns: undefined
      }
    }
    Enums: {
      attendance_status: AttendanceStatusEnum
    }
    CompositeTypes: { [key: string]: never }
  }
}
// --- END OF TYPE DEFINITIONS ---


// WARNING: In a real-world application, DO NOT hardcode your credentials like this.
// These values should be stored securely in environment variables and accessed
// via `process.env.SUPABASE_URL` and `process.env.SUPABASE_KEY`.
// This is done here only for demonstration purposes in this specific sandboxed environment.
const supabaseUrl = 'https://qurvymoragyykcneuhxg.supabase.co';
const supabaseKey = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InF1cnZ5bW9yYWd5eWtjbmV1aHhnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE1OTUzNDMsImV4cCI6MjA2NzE3MTM0M30.RP-fTDIX-vMYevElUEjILaC5N_zFmV1vlfGp_UHFQYs';

export const supabase = createClient<Database>(supabaseUrl, supabaseKey);


/*
  =====================================================================
  SKEMA SQL SUPABASE (VERSI 11.0 - MODEL DATA KOLABORATIF)
  =====================================================================
  
  Salin dan tempel SELURUH kode di bawah ini ke dalam SQL Editor di dashboard Supabase.
  Skrip ini MENGUBAH APLIKASI menjadi mode kolaboratif di mana SEMUA GURU BERBAGI DATA SISWA & ABSENSI YANG SAMA.
  Aman untuk dijalankan berkali-kali.

  -- Bagian 1: Pastikan tipe dan tabel dasar ada.
  DO $$ BEGIN
      CREATE TYPE public.attendance_status AS ENUM ('Hadir', 'Sakit', 'Izin', 'Alfa');
  EXCEPTION
      WHEN duplicate_object THEN null;
  END $$;

  CREATE TABLE IF NOT EXISTS public.students (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    user_id UUID NOT NULL DEFAULT auth.uid() REFERENCES auth.users(id) ON DELETE CASCADE,
    name TEXT NOT NULL,
    class TEXT NOT NULL,
    nis TEXT NOT NULL DEFAULT '',
    email TEXT
  );
  
  CREATE TABLE IF NOT EXISTS public.attendance_records (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    student_id BIGINT NOT NULL REFERENCES public.students(id) ON DELETE CASCADE,
    user_id UUID NOT NULL DEFAULT auth.uid() REFERENCES auth.users(id) ON DELETE CASCADE,
    date DATE NOT NULL,
    lesson_hour INTEGER NOT NULL,
    status public.attendance_status NOT NULL 
  );
  
  -- Bagian 2: Ubah UNIQUE constraint untuk absensi.
  -- Kunci unik sekarang hanya pada siswa, tanggal, dan jam, memungkinkan kolaborasi.
  -- user_id sekarang hanya melacak siapa yang terakhir mengubahnya.
  ALTER TABLE public.attendance_records DROP CONSTRAINT IF EXISTS unique_attendance_record;
  ALTER TABLE public.attendance_records
    ADD CONSTRAINT unique_attendance_record UNIQUE (student_id, date, lesson_hour);

  -- Bagian 3: Aktifkan Row Level Security (RLS) jika belum aktif.
  ALTER TABLE public.students ENABLE ROW LEVEL SECURITY;
  ALTER TABLE public.attendance_records ENABLE ROW LEVEL SECURITY;
  
  -- Bagian 4: Hapus semua kebijakan RLS lama untuk diganti dengan kebijakan kolaboratif.
  -- Ini menghapus kebijakan lama yang membatasi data per pengguna.
  DROP POLICY IF EXISTS "Users can view their own students." ON public.students;
  DROP POLICY IF EXISTS "Users can insert their own students." ON public.students;
  DROP POLICY IF EXISTS "Users can update their own students." ON public.students;
  DROP POLICY IF EXISTS "Users can delete their own students." ON public.students;
  DROP POLICY IF EXISTS "Users can view their own attendance." ON public.attendance_records;
  DROP POLICY IF EXISTS "Users can insert their own attendance." ON public.attendance_records;
  DROP POLICY IF EXISTS "Users can update their own attendance." ON public.attendance_records;
  DROP POLICY IF EXISTS "Users can delete their own attendance." ON public.attendance_records;
  -- Hapus juga kebijakan dari versi kolaboratif sebelumnya jika ada, untuk pembaruan
  DROP POLICY IF EXISTS "Authenticated users can manage students." ON public.students;
  DROP POLICY IF EXISTS "Authenticated users can manage attendance." ON public.attendance_records;


  -- Bagian 5: Buat kebijakan RLS baru untuk model data bersama (kolaboratif).
  -- Kebijakan ini mengizinkan setiap pengguna yang terotentikasi untuk mengelola SEMUA data.
  CREATE POLICY "Authenticated users can manage students"
    ON public.students FOR ALL
    TO authenticated
    USING (true)
    WITH CHECK (true);

  CREATE POLICY "Authenticated users can manage attendance"
    ON public.attendance_records FOR ALL
    TO authenticated
    USING (true)
    WITH CHECK (true);

  -- Bagian 6: Ganti fungsi RPC dengan versi UPSERT yang lebih efisien dan kolaboratif.
  -- Fungsi ini sekarang melakukan 'upsert' (update atau insert) dalam satu operasi atomik.
  DROP FUNCTION IF EXISTS public.save_class_attendance(jsonb);

  CREATE OR REPLACE FUNCTION public.save_class_attendance(records_json jsonb)
  RETURNS void
  LANGUAGE plpgsql
  SECURITY DEFINER
  AS $$
  DECLARE
      record jsonb;
      v_student_id bigint;
      v_date date;
      v_lesson_hour integer;
      v_status public.attendance_status;
      caller_user_id uuid := auth.uid();
  BEGIN
      FOR record IN (SELECT * FROM jsonb_array_elements(records_json))
      LOOP
          -- Ekstrak dan validasi data dari JSON
          v_student_id  := (record->>'studentId')::bigint;
          v_date        := (record->>'date')::date;
          v_lesson_hour := (record->>'lessonHour')::integer;
          v_status      := (record->>'status')::public.attendance_status;

          IF v_student_id IS NULL OR v_date IS NULL OR v_lesson_hour IS NULL OR v_status IS NULL THEN
              RAISE EXCEPTION 'Data absensi tidak lengkap: %', record;
          END IF;

          -- Lakukan operasi UPSERT (Update or Insert)
          INSERT INTO public.attendance_records (student_id, date, lesson_hour, status, user_id)
          VALUES (v_student_id, v_date, v_lesson_hour, v_status, caller_user_id)
          ON CONFLICT (student_id, date, lesson_hour)
          DO UPDATE SET
            status = EXCLUDED.status,
            user_id = EXCLUDED.user_id; -- Update status dan user_id ke yang terbaru
      END LOOP;
  END;
  $$;
*/
