
import { createClient } from '@supabase/supabase-js';

// --- START OF TYPE DEFINITIONS ---
export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export type AttendanceStatusEnum = 'Hadir' | 'Sakit' | 'Izin' | 'Alfa';

export interface Database {
  public: {
    Tables: {
      students: {
        Row: {
          id: number
          created_at: string
          name: string
          class: string
          nis: string
          email: string | null
          user_id: string
        }
        Insert: {
          id?: number
          created_at?: string
          name: string
          class: string
          nis?: string
          email?: string | null
          user_id?: string
        }
        Update: {
          id?: number
          created_at?: string
          name?: string
          class?: string
          nis?: string
          email?: string | null
          user_id?: string
        }
        Relationships: []
      }
      attendance_records: {
        Row: {
          id: number
          created_at: string
          student_id: number
          date: string
          lesson_hour: number
          status: AttendanceStatusEnum
          user_id: string
        }
        Insert: {
          id?: number
          created_at?: string
          student_id: number
          date: string
          lesson_hour: number
          status: AttendanceStatusEnum
          user_id?: string
        }
        Update: {
          id?: number
          created_at?: string
          student_id?: number
          date?: string
          lesson_hour?: number
          status?: AttendanceStatusEnum
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "attendance_records_student_id_fkey"
            columns: ["student_id"]
            isOneToOne: false
            referencedRelation: "students"
            referencedColumns: ["id"]
          }
        ]
      }
    }
    Views: { [key: string]: never }
    Functions: { [key: string]: never }
    Enums: {
      attendance_status: AttendanceStatusEnum
    }
    CompositeTypes: { [key: string]: never }
  }
}
// --- END OF TYPE DEFINITIONS ---


// WARNING: In a real-world application, DO NOT hardcode your credentials like this.
// These values should be stored securely in environment variables and accessed
// via `process.env.SUPABASE_URL` and `process.env.SUPABASE_KEY`.
// This is done here only for demonstration purposes in this specific sandboxed environment.
const supabaseUrl = 'https://qurvymoragyykcneuhxg.supabase.co';
const supabaseKey = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InF1cnZ5bW9yYWd5eWtjbmV1aHhnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE1OTUzNDMsImV4cCI6MjA2NzE3MTM0M30.RP-fTDIX-vMYevElUEjILaC5N_zFmV1vlfGp_UHFQYs';

export const supabase = createClient<Database>(supabaseUrl, supabaseKey);


/*
  ==============================================================
  SKEMA SQL SUPABASE YANG DIREKOMENDASIKAN (VERSI 3.0 - MULTI-USER)
  ==============================================================
  
  Salin dan tempel kode di bawah ini ke dalam SQL Editor di dashboard Supabase.
  Skrip ini SANGAT PENTING untuk keamanan data antar pengguna.

  -- 1. Buat tipe ENUM untuk status absensi jika belum ada.
  DO $$ BEGIN
      CREATE TYPE public.attendance_status AS ENUM ('Hadir', 'Sakit', 'Izin', 'Alfa');
  EXCEPTION
      WHEN duplicate_object THEN null;
  END $$;

  -- 2. Buat tabel 'students' (dengan relasi ke user).
  create table if not exists public.students (
    id bigint generated by default as identity primary key,
    created_at timestamp with time zone not null default now(),
    user_id uuid not null default auth.uid() references auth.users(id) on delete cascade,
    name text not null,
    class text not null,
    nis text not null default '',
    email text
  );
  
  -- 3. Buat tabel 'attendance_records' (dengan relasi ke user).
  create table if not exists public.attendance_records (
    id bigint generated by default as identity primary key,
    created_at timestamp with time zone not null default now(),
    student_id bigint not null references public.students(id) on delete cascade,
    user_id uuid not null default auth.uid() references auth.users(id) on delete cascade,
    date date not null,
    lesson_hour integer not null,
    status public.attendance_status not null 
  );
  
  -- 4. Tambahkan UNIQUE constraint (termasuk user_id) agar upsert berfungsi per-user.
  alter table public.attendance_records drop constraint if exists unique_attendance_record;
  alter table public.attendance_records
    add constraint unique_attendance_record unique (student_id, date, lesson_hour, user_id);

  -- 5. Aktifkan Row Level Security (RLS) untuk kedua tabel.
  alter table public.students enable row level security;
  alter table public.attendance_records enable row level security;
  
  -- 6. HAPUS kebijakan lama yang tidak aman.
  drop policy if exists "Public Access" on public.students;
  drop policy if exists "Public Access" on public.attendance_records;

  -- 7. BUAT kebijakan BARU yang AMAN untuk tabel 'students'.
  -- Pengguna hanya bisa melihat datanya sendiri.
  drop policy if exists "Users can view their own students." on public.students;
  create policy "Users can view their own students." on public.students for select using (auth.uid() = user_id);

  -- Pengguna hanya bisa menambah data untuk dirinya sendiri.
  drop policy if exists "Users can insert their own students." on public.students;
  create policy "Users can insert their own students." on public.students for insert with check (auth.uid() = user_id);

  -- Pengguna hanya bisa mengubah datanya sendiri.
  drop policy if exists "Users can update their own students." on public.students;
  create policy "Users can update their own students." on public.students for update using (auth.uid() = user_id);

  -- Pengguna hanya bisa menghapus datanya sendiri.
  drop policy if exists "Users can delete their own students." on public.students;
  create policy "Users can delete their own students." on public.students for delete using (auth.uid() = user_id);


  -- 8. BUAT kebijakan BARU yang AMAN untuk tabel 'attendance_records'.
  -- Kebijakan ini mengikuti pola yang sama dengan tabel students.
  drop policy if exists "Users can view their own attendance." on public.attendance_records;
  create policy "Users can view their own attendance." on public.attendance_records for select using (auth.uid() = user_id);

  drop policy if exists "Users can insert their own attendance." on public.attendance_records;
  create policy "Users can insert their own attendance." on public.attendance_records for insert with check (auth.uid() = user_id);

  drop policy if exists "Users can update their own attendance." on public.attendance_records;
  create policy "Users can update their own attendance." on public.attendance_records for update using (auth.uid() = user_id);

  drop policy if exists "Users can delete their own attendance." on public.attendance_records;
  create policy "Users can delete their own attendance." on public.attendance_records for delete using (auth.uid() = user_id);

*/
