
import { createClient } from '@supabase/supabase-js';

// --- START OF TYPE DEFINITIONS ---
export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export type AttendanceStatusEnum = 'Hadir' | 'Sakit' | 'Izin' | 'Alfa';

export interface Database {
  public: {
    Tables: {
      students: {
        Row: {
          id: number
          created_at: string
          name: string
          class: string
          nis: string
          email: string | null
        }
        Insert: {
          id?: number
          created_at?: string
          name: string
          class: string
          nis?: string
          email?: string | null
        }
        Update: {
          id?: number
          created_at?: string
          name?: string
          class?: string
          nis?: string
          email?: string | null
        }
        Relationships: []
      }
      attendance_records: {
        Row: {
          id: number
          created_at: string
          student_id: number
          date: string
          lesson_hour: number
          status: AttendanceStatusEnum
        }
        Insert: {
          id?: number
          created_at?: string
          student_id: number
          date: string
          lesson_hour: number
          status: AttendanceStatusEnum
        }
        Update: {
          id?: number
          created_at?: string
          student_id?: number
          date?: string
          lesson_hour?: number
          status?: AttendanceStatusEnum
        }
        Relationships: [
          {
            foreignKeyName: "attendance_records_student_id_fkey"
            columns: ["student_id"]
            isOneToOne: false
            referencedRelation: "students"
            referencedColumns: ["id"]
          }
        ]
      }
    }
    Views: { [key: string]: never }
    Functions: {
      save_class_attendance: {
        Args: {
          records_json: Json
        }
        Returns: undefined
      }
    }
    Enums: {
      attendance_status: AttendanceStatusEnum
    }
    CompositeTypes: { [key: string]: never }
  }
}
// --- END OF TYPE DEFINITIONS ---


// WARNING: In a real-world application, DO NOT hardcode your credentials like this.
// These values should be stored securely in environment variables and accessed
// via `process.env.SUPABASE_URL` and `process.env.SUPABASE_KEY`.
// This is done here only for demonstration purposes in this specific sandboxed environment.
const supabaseUrl = 'https://qurvymoragyykcneuhxg.supabase.co';
const supabaseKey = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InF1cnZ5bW9yYWd5eWtjbmV1aHhnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE1OTUzNDMsImV4cCI6MjA2NzE3MTM0M30.RP-fTDIX-vMYevElUEjILaC5N_zFmV1vlfGp_UHFQYs';

export const supabase = createClient<Database>(supabaseUrl, supabaseKey);


/*
  =====================================================================
  SKEMA SQL SUPABASE (VERSI 12.0 - FINALISASI MODEL KOLABORATIF)
  =====================================================================
  
  Salin dan tempel SELURUH kode di bawah ini ke dalam SQL Editor di dashboard Supabase.
  Skrip ini MENGHAPUS kolom 'user_id' yang sudah tidak diperlukan lagi, yang menjadi akar masalah
  kesulitan login bagi user baru. Ini adalah langkah terakhir untuk menstabilkan model data kolaboratif.
  Aman untuk dijalankan berkali-kali.

  -- Bagian 1: Hapus kolom 'user_id' dari tabel students jika ada.
  DO $$
  BEGIN
      IF EXISTS (
          SELECT 1
          FROM information_schema.columns
          WHERE table_schema = 'public'
          AND table_name = 'students'
          AND column_name = 'user_id'
      ) THEN
          ALTER TABLE public.students DROP COLUMN user_id;
      END IF;
  END $$;

  -- Bagian 2: Hapus kolom 'user_id' dari tabel attendance_records jika ada.
  DO $$
  BEGIN
      IF EXISTS (
          SELECT 1
          FROM information_schema.columns
          WHERE table_schema = 'public'
          AND table_name = 'attendance_records'
          AND column_name = 'user_id'
      ) THEN
          ALTER TABLE public.attendance_records DROP COLUMN user_id;
      END IF;
  END $$;

  -- Bagian 3: Pastikan tabel dan tipe dasar ada (jika dijalankan pada proyek baru)
  DO $$ BEGIN
      CREATE TYPE public.attendance_status AS ENUM ('Hadir', 'Sakit', 'Izin', 'Alfa');
  EXCEPTION WHEN duplicate_object THEN null; END $$;

  CREATE TABLE IF NOT EXISTS public.students (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    name TEXT NOT NULL,
    class TEXT NOT NULL,
    nis TEXT NOT NULL DEFAULT '',
    email TEXT
  );

  CREATE TABLE IF NOT EXISTS public.attendance_records (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    student_id BIGINT NOT NULL REFERENCES public.students(id) ON DELETE CASCADE,
    date DATE NOT NULL,
    lesson_hour INTEGER NOT NULL,
    status public.attendance_status NOT NULL
  );
  
  -- Bagian 4: Pastikan RLS dan unique constraint sudah benar.
  ALTER TABLE public.attendance_records DROP CONSTRAINT IF EXISTS unique_attendance_record;
  ALTER TABLE public.attendance_records ADD CONSTRAINT unique_attendance_record UNIQUE (student_id, date, lesson_hour);

  ALTER TABLE public.students ENABLE ROW LEVEL SECURITY;
  ALTER TABLE public.attendance_records ENABLE ROW LEVEL SECURITY;
  
  -- Bagian 5: Hapus kebijakan RLS lama dan pastikan kebijakan kolaboratif ada.
  DROP POLICY IF EXISTS "Users can view their own students" ON public.students;
  DROP POLICY IF EXISTS "Users can insert their own students" ON public.students;
  DROP POLICY IF EXISTS "Users can update their own students" ON public.students;
  DROP POLICY IF EXISTS "Users can delete their own students" ON public.students;
  DROP POLICY IF EXISTS "Users can view their own attendance" ON public.attendance_records;
  DROP POLICY IF EXISTS "Users can insert their own attendance" ON public.attendance_records;
  DROP POLICY IF EXISTS "Users can update their own attendance" ON public.attendance_records;
  DROP POLICY IF EXISTS "Users can delete their own attendance" ON public.attendance_records;
  
  DROP POLICY IF EXISTS "Authenticated users can manage students" ON public.students;
  CREATE POLICY "Authenticated users can manage students"
    ON public.students FOR ALL
    TO authenticated
    USING (true) WITH CHECK (true);

  DROP POLICY IF EXISTS "Authenticated users can manage attendance" ON public.attendance_records;
  CREATE POLICY "Authenticated users can manage attendance"
    ON public.attendance_records FOR ALL
    TO authenticated
    USING (true) WITH CHECK (true);

  -- Bagian 6: Perbarui fungsi RPC untuk bekerja tanpa user_id.
  -- Fungsi ini sudah tidak memerlukan SECURITY DEFINER karena RLS sudah mengizinkan akses.
  CREATE OR REPLACE FUNCTION public.save_class_attendance(records_json jsonb)
  RETURNS void
  LANGUAGE plpgsql
  AS $$
  DECLARE
      record jsonb;
      v_student_id bigint;
      v_date date;
      v_lesson_hour integer;
      v_status public.attendance_status;
  BEGIN
      FOR record IN (SELECT * FROM jsonb_array_elements(records_json))
      LOOP
          v_student_id  := (record->>'studentId')::bigint;
          v_date        := (record->>'date')::date;
          v_lesson_hour := (record->>'lessonHour')::integer;
          v_status      := (record->>'status')::public.attendance_status;

          IF v_student_id IS NULL OR v_date IS NULL OR v_lesson_hour IS NULL OR v_status IS NULL THEN
              RAISE EXCEPTION 'Data absensi tidak lengkap: %', record;
          END IF;

          INSERT INTO public.attendance_records (student_id, date, lesson_hour, status)
          VALUES (v_student_id, v_date, v_lesson_hour, v_status)
          ON CONFLICT (student_id, date, lesson_hour)
          DO UPDATE SET status = EXCLUDED.status;
      END LOOP;
  END;
  $$;
*/
